Option Explicit

Public Const TITLE_SEL As String = "Sel"
Public Const TITLE_FILENAME As String = "FileName"
Public Const TITLE_LINKTO As String = "LinkTo"
Public Const TITLE_MODELIDDRAWID As String = "ModelID/DrawingID"
Public Const TITLE_FILEDATANAME As String = "File_Data_Name"
Public Const TITLE_FULLDESIGNNO As String = "Full_Design_No"
Public Const TITLE_FILEDATATYPE As String = "File_Data_Type"
Public Const TITLE_DESIGNNO As String = "Design_No"
Public Const TITLE_REVISIONNO As String = "Revision_No"
Public Const TITLE_SECTION As String = "Section"
Public Const TITLE_CURRENTSTATUS As String = "Current_Status"
Public Const TITLE_PROCESS As String = "Process"
Public Const TITLE_DESIGNER As String = "Designer"
Public Const TITLE_CLASSIFICATION As String = "Classification"
Public Const TITLE_MATERIALGRADE As String = "Material_Grade"
Public Const CELL_MAIN_FIXED As String = "B12"
Public Const CELL_MAIN_USER As String = "M12"
Public Const CELL_MAIN_DESIGNER_NAME As String = "P2"
Public Const CELL_MAIN_DESIGNER As String = "Q2"
Public Const SHEET_DEFINE_DEVELOPMENT As String = "Define_Development"
Public Const CELL_DEFINE_DEVELOPMENT As String = "B5"
Public Const CELL_DEFINE_DRAWING As String = "B5"
Public Const CELL_SETTING As String = "D5"
Public Const CELL_ALIAS As String = "L5"
Public Const CELL_DEBUG_DESIGNNO As String = "E2"
Public Const COLOR_DISABLED As Long = 14211288
Public Const COLOR_REQUIRED As Long = 10092543
Public Const COLOR_INDEX_IN3DEX As Long = 10
Public Const COLOR_ODD_ROW As Long = 13494015
Public Const VALUE_INTERNALDATA As String = "Internal data"
Public Const VALUE_SUBMISSIONDATA As String = "Submission data"
Public Const VALUE_2KMOULD As String = "2K mould (CATPart)"
Public Const VALUE_SUBPRODUCT As String = "SubProduct"
Public Const VALUE_REFERENCE As String = "Reference"
Public Const VALUE_LAYOUT As String = "LayOut"
Public Const VALUE_CUSTOMERAPPROVEDDATA As String = "Customer approved data"
Public Const VALUE_MASSPRODUCT As String = "Mass production"
Public Const VALUE_PROTOTYPESTUDY As String = "Prototype/Study"
Public Const VALUE_PROTOTYPE As String = "Prototype"
Public Const VALUE_STUDY As String = "Study"
Public Const VALUE_FCSEPWR As String = "FCS/e-Pwr"
Public Const VALUE_FCS As String = "FCS"
Public Const VALUE_EPWR As String = "PWR"
Public Const VALUE_UNSET_STR = "Unset"
Public Const VALUE_UNSET_NUM = "999"
Public Const REPLACE_CHAR As String = " "
Public Const REPLACE_NEW_LINE_DRAWTEXT As String = " "
Public glstProhibitCharacter() As String
Public Const CATDRAWING As String = "CATDrawing"
Public Const CATPRODUCT As String = "CATProduct"
Public Const CATPART As String = "CATPart"

Public Sub Init()
    ReDim glstProhibitCharacter(18)
    glstProhibitCharacter(1) = "/"
    glstProhibitCharacter(2) = """"
    glstProhibitCharacter(3) = "#"
    glstProhibitCharacter(4) = "$"
    glstProhibitCharacter(5) = "@"
    glstProhibitCharacter(6) = "%"
    glstProhibitCharacter(7) = "*"
    glstProhibitCharacter(8) = "?"
    glstProhibitCharacter(9) = "\"
    glstProhibitCharacter(10) = "<"
    glstProhibitCharacter(11) = ">"
    glstProhibitCharacter(12) = "["
    glstProhibitCharacter(13) = "]"
    glstProhibitCharacter(14) = "|"
    glstProhibitCharacter(15) = ":"
    glstProhibitCharacter(16) = "'"
    glstProhibitCharacter(17) = ";"
    glstProhibitCharacter(18) = "!"
End Sub